### ISSUE TITLE
[OSX] Couldn't posix_spawn error 8, when --synthesize option is passed to bosy

### ISSUE THREAD

**Issue by bbiiggppiigg** [reactive-systems/bosy#1]
As title, when I tried to use the --synthesize option on OSX, an error is reported.
And I think the issue is related to the use of some linux-64 bit binaries

For example, in Solver.swift line 528
it tries to launch a binary under Tools/quabscm, which turns out to be a 64bit ELF executable
When I checked the make file, it is downloaded from a dropbox link, with only the linux binary in it.

Under the folder Tools, there are actually 4 binaries that are ELF executable instead of Mac-O executable:
caqem, hqs-linux, quabscm,vampire, that can likely cause the same problem.

So I'm just wandering if you would kindly provide the Mac-Version binary as well ?

**Comment by ltentrup** [comment]
I've added the macOS binary of quabscm in 697796eb7aa6c471dff9aba10ce5c6855334afcf since it is used in the standard configuration for synthesis. The others are less important (and some not available for macOS).

**Comment by bbiiggppiigg** [comment]
Thank you really much
