### ISSUE TITLE
Encounters error in running the example HyperLTL spec in BoSy

### ISSUE THREAD

**Issue by SivarajeshA** [reactive-systems/bosy#11]
Environment : Ubuntu 20.04

I have installed the swift 
Done BoSy make 
Installed other packages mentioned in the git page for Ubuntu 20.04 

When I try to run : swift run -c release BoSyHyper Samples/HyperLTL/SecretDecision.bosy
I got the below error
##########
[1/1] Planning build

* Build Completed!info: Linear automaton contains 4 states
info: Hyper automaton contains 1 states
info: build encoding for bound 1
(set-logic UFDTLIA)
.
.
.
Foundation/Process.swift:388: Fatal error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."
Illegal instruction (core dumped)
##########

I have added complete output as attachment file

Kindly help me to fix this issue.

**Comment by GamerPanda99** [comment]
Hey
I could not reproduce the Error on my VM form just the command you used.
I could not find the file you attached, could you please upload it again? Without it we're not really able to help you with your issue

Thanks

**Comment by SivarajeshA** [comment]
sorry, here is the file
[BoSy_err.txt](https://github.com/reactive-systems/bosy/files/6528393/BoSy_err.txt)

**Comment by SivarajeshA** [comment]
I want the SMV output from this offline tool, what is the command to generate the same ?

Can I run HyperLTL in online interface ? If so what's the format?

**Comment by nimetz** [comment]
Hi, 
can you compare the binaries in Tools/ with the list in the makefile? Looks like some external call was impossible.

The online interface does not support HyperLTL currently.

**Comment by SivarajeshA** [comment]
Thanks @nimetz for your response

I tried installing swift & bosy in other Ubuntu system and tried the same hyperLTL example, I faced the same issue.

I have attached the result of make file and hyperLTL output file for more information, kindly do check and help me to resolve this issue
[hyperLTL_output.txt](https://github.com/reactive-systems/bosy/files/6541617/hyperLTL_output.txt)
[make_all_output.txt](https://github.com/reactive-systems/bosy/files/6541618/make_all_output.txt)
[make_all_output_2.txt](https://github.com/reactive-systems/bosy/files/6541619/make_all_output_2.txt)

In my work I wanna make use of the SMV output of HyperLTL from this tool, therefore kindly confirm whether the SMV will be generated for HyperLTL or not?

**Comment by GamerPanda99** [comment]
From skimming over your build logs it seems that a download location for a tool is no longer available or I messed up the link wenn fixing the Makefile. I will check that once I am in front of my machine again. Maybe that produces your error

**Comment by nimetz** [comment]
The output of BoSyHyper is in .dot and .aag format, but you can easily add the line `print((solution as! SmvRepresentable).smv)` to file /Sources/BoSyHyper/main.swift in line 118, and it will print also the .smv representable of the solution to stdout.

To have a quick fix for the Tool error before we fix it, please comment out line 55 in the makefile and try compiling again (If necessary, repeat that for every curl that didn't work). You can add the binary of idq later on, but BoSyHyper does not use it.

**Comment by SivarajeshA** [comment]
Thanks @nimetz I have 

> The output of BoSyHyper is in .dot and .aag format, but you can easily add the line `print((solution as! SmvRepresentable).smv)` to file /Sources/BoSyHyper/main.swift in line 118, and it will print also the .smv representable of the solution to stdout.
> 
> To have a quick fix for the curl error of idq before we fix it, please comment out line 55 in the makefile and try compiling again (If necessary, repeat that for every curl that didn't work). You can add the binary of idq later on, but BoSyHyper does not use it.

Thank you @nimetz 
I have made the changes as you said, check new log files below
[make_log.txt](https://github.com/reactive-systems/bosy/files/6545869/make_log.txt)
[hyperLTL_output_log.txt](https://github.com/reactive-systems/bosy/files/6545871/hyperLTL_output_log.txt)

suggest me further changes to fix the issue.

**Comment by nimetz** [comment]
Seems fine, to execute synthesis you need to add the --synthesize flag to the call, otherwise only realizability is checked: 
`swift run -c release BoSyHyper --synthesize Samples/HyperLTL/SecretDecision.bosy`

The unsupported logic error is an error from z3, based on your make output I would assume the correct z3 version is installed. You should validate that the z3 --version is 4.8.7.

**Comment by SivarajeshA** [comment]
> Seems fine, to execute synthesis you need to add the --synthesize flag to the call, otherwise only realizability is checked:
> `swift run -c release BoSyHyper --synthesize Samples/HyperLTL/SecretDecision.bosy`
> 
> The unsupported logic error is an error from z3, based on your make output I would assume the correct z3 version is installed. You should validate that the z3 --version is 4.8.7.

I have the latest version of z3 which is 4.8.10, So i need to downgrade to use this tool?

**Comment by nimetz** [comment]
yes, looks fine!
