### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by brianlheim** [reactive-systems/bosy#2]
Environment:

OS: macOS 10.13.3 Beta
swiftc version: 4.0.3

I got a few errors while trying to build bosy:

While building `ltl3ba`:

```bash
cd Tools ; curl -OL https://sourceforge.net/projects/ltl3ba/files/ltl3ba/1.1/ltl3ba-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   746  100   746    0     0   1286      0 --:--:-- --:--:-- --:--:--  1286
cd Tools ; tar xzf ltl3ba-1.1.3.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make: *** [Tools/ltl3ba-1.1.3] Error 1
rm Tools/ltl3ba-1.1.3.tar.gz
```

I downloaded the tarball manually from Sourceforge and edited out that part of the Makefile. Then:

```bash
cd Tools ; make -C ltl3ba-1.1.3
g++  -O3 -DNXT -I/usr/local/include/  -c -o parse.o parse.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
In file included from parse.c:36:
./ltl3ba.h:40:10: fatal error: 'bdd.h' file not found
#include <bdd.h>
         ^~~~~~~
1 error generated.
make[1]: *** [parse.o] Error 1
make: *** [Tools/ltl3ba-1.1.3/ltl3ba] Error 2
```

I determined this is because ltl3ba requires BuDDy (according to that project's readme). So, I downloaded v 2.4 from Sourceforge, then:

```bash
tar xzf buddy-2.4.tar.gz
cd buddy-2.4
./configure && make
make install
```

I didn't mind installing these to my system, but ideally if this were a part of building these directories would be installed more locally.

After that things seem to go OK, although I got this warning on each file:

```
cd Tools ; make -C ltl3ba-1.1.3
g++  -O3 -DNXT -I/usr/local/include/  -c -o parse.o parse.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
In file included from parse.c:36:
./ltl3ba.h:241:15: warning: 'print_set_out' has C-linkage specified, but returns user-defined type 'std::ostream &' (aka 'basic_ostream<char> &') which is incompatible with C [-Wreturn-type-c-linkage]
std::ostream& print_set_out(std::ostream &, int *, int);
              ^
1 warning generated.
```

After that, I ran the simple_arbiter sample and it seemed to work OK.

**Comment by ltentrup** [comment]
Thanks for your comments (and sorry for the late reply). Yes, the build system is fragile, especially due to the vast amount of dependencies. Unfortunately, there currently seems to be no better solution (we cannot provide a pre-compiled version, or even a Docker image as the licenses of some dependencies does not allow this).

**Comment by brianlheim** [comment]
No worries, I understand. I would appreciate it if you documented the BuDDy dependency specifically, since it took awhile to figure out that that was what I was missing. Other than that I just figured I would share so that anyone else running into the same issues might see this. Feel free to close/document as you like.

**Comment by brianlheim** [comment]
That was all I noticed! Thanks!
