### ISSUE TITLE
Error on dependencies when trying a fresh build

### ISSUE THREAD

**Issue by dh73** [reactive-systems/bosy#3]
When trying to build, seems that there's an issue in Swift dependency graph file (I'm not sure of this, never used Swift before, I'm not sure how it handles dependencies).

cp Tools/spot-2.5/bin/ltl2tgba Tools/
swift build --configuration release -Xcc -O3 -Xcc -DNDEBUG -Xswiftc -Ounchecked
Updating https://github.com/ltentrup/CAiger.git
Updating https://github.com/ltentrup/SafetySynth.git
Updating https://github.com/apple/swift-package-manager.git
Updating https://github.com/ltentrup/CUDD.git
error: dependency graph is unresolvable; found these conflicting requirements:

**Dependencies: 
    https://github.com/ltentrup/CAiger.git @ 0.1.0..<1.0.0
    https://github.com/ltentrup/CUDD.git @ 0.2.0..<1.0.0
make: *** [Makefile:11: release] Error 1**

**Comment by dh73** [comment]
Seems that I've used latest Swift compiler version which isn't able to compile Bosy. I think the link to Swift download in the Readme should point to Bosy supported version (4.x) instead.

**Comment by ltentrup** [comment]
Thanks for reporting! Swift 5 broke the build due to dropping backwards compatibility.
I just pushed an update that should solve the build error.

**Comment by dh73** [comment]
Thank you so much!
